#!/bin/bash
export ASDF_PYTHON_VERSION="3.13.5"

source $(brew --prefix)/opt/asdf/libexec/asdf.sh

asdf list python $ASDF_PYTHON_VERSION 1>&2 > /dev/null

if [ $? -ne 0 ]; then
  asdf plugin add python 2> /dev/null
  asdf install python
fi

~/.bin/ssh-ident/ssh-ident $@
